name: kanban_tracker
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.2.0
  cupertino_icons: ^1.0.2
  json_annotation: ^4.7.0
  injectable: ^2.1.0
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  intl: ^0.17.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  easy_localization: ^3.0.1
  auto_route: ^5.0.4
  fluttertoast: ^8.1.2
  cloud_firestore: ^4.3.1
  uuid: ^3.0.7
  csv: ^5.0.1
  path_provider: ^2.0.12
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  injectable_generator: ^2.1.3
  auto_route_generator: ^5.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/localizations/
