// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOUM90uROLjue21pmfmhCzX6FKfPY4JKA',
    appId: '1:985187200437:android:ea2ac44ca29162144bbdfc',
    messagingSenderId: '985187200437',
    projectId: 'kanbantest-2e9ea',
    databaseURL: 'https://kanbantest-2e9ea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kanbantest-2e9ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_1MhNhWX8NNZM5Kzq90UuyOufNrGIZdk',
    appId: '1:985187200437:ios:441fa7e570e132944bbdfc',
    messagingSenderId: '985187200437',
    projectId: 'kanbantest-2e9ea',
    databaseURL: 'https://kanbantest-2e9ea-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kanbantest-2e9ea.appspot.com',
    iosClientId: '985187200437-2866nvlg8sj6starjed4cvflc058trd7.apps.googleusercontent.com',
    iosBundleId: 'com.daniqshu.kanbanTracker',
  );
}
